apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eks-db-deploy
  name: eks-db-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: eks-db-deploy
  type: ClusterIP
status:
  loadBalancer: {}