apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
